### ISSUE TITLE
求添加自定义媒体库展示范围和展示顺序

### ISSUE THREAD

**Issue by onelxzy** [newday-life/emby-front-end-mod#1]
1.有9kg库不想在首页展示，现有的那句根据tmdb是否有信息判断的方法（this.itemQuery.HasTmdbId = true;// true为TheMovieDb削刮到的影视(应可排除jav之类的)），会导致那个库依然存在，只是显示的空白页【一个影视都没有】很不美观，希望大佬能够优化一下。

2.另外就是希望大佬能添加一下自定义海报排序方法的功能，比如我想让海报以最新一集添加日期倒序排列，我像在emby-crx上那样将sort by改为SortBy: "DateLastContentAdded,SortName"，但发现它似乎不生效，还是随机顺序展示的。

3.另外就是不知道为什么，我使用这个js脚本之后，在轮播页左下角显示的几个库的信息，排序第一的库不在其中。

**Comment by newday-life** [comment]
1.已加设置，在设置-主页 。
2.因为有缓存，第二天生效，但最终的结果顺序还是会被打乱。
3.不知道
