### ISSUE TITLE
能否设置非固定的媒体轮播图

### ISSUE THREAD

**Issue by morisama11** [newday-life/emby-front-end-mod#14]
目前轮播图是按照发行日期排序，把SortBy: "ProductionYear, PremiereDate, SortName"改成SortBy: "Random"没有效果，是哪里还需要修改吗

**Comment by newday-life** [comment]
第二天生效，缓存一天。

**Comment by Mr54233** [comment]
我想改成按最新入库的来展示这个字段应该写什么啊
