### ISSUE TITLE
【功能请求】一直想要一个AppleTV那样，首页自动播放预告片的效果

### ISSUE THREAD

**Issue by jackloves111** [newday-life/emby-front-end-mod#2]
感觉比图片来的效果更强烈，只是需要自己手动维护预告片到搜刮目录，这个我个人问题不大的

**Comment by jackloves111** [comment]
https://github.com/newday-life/emby-front-end-mod/assets/25839463/d4826e18-9d8e-4360-8f72-d58189d4af5d

大佬竟然真的在搞预告片的，期待

**Comment by newday-life** [comment]
多加了文件试试水，可以试试
